import { ArrowRight, FileCode, TestTube, Workflow, CheckCircle2 } from "lucide-react";

const steps = [
  {
    icon: FileCode,
    title: "Input Requirements",
    description: "Natural language or structured specifications",
    status: "complete",
  },
  {
    icon: Workflow,
    title: "AI Generation",
    description: "Requirements, architecture, source code",
    status: "active",
  },
  {
    icon: TestTube,
    title: "Test Generation",
    description: "Automated test cases and scenarios",
    status: "pending",
  },
  {
    icon: CheckCircle2,
    title: "Simulation Validation",
    description: "CARLA Simulator verification",
    status: "pending",
  },
];

export const WorkflowSection = () => {
  return (
    <section className="py-24 px-6 relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-background via-secondary/20 to-background" />
      
      <div className="max-w-6xl mx-auto relative z-10">
        <div className="text-center mb-16">
          <span className="inline-block px-4 py-1.5 rounded-full text-xs font-medium bg-accent/10 text-accent border border-accent/20 mb-4">
            Pipeline
          </span>
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            End-to-End AI Workflow
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            From high-level inputs to validated vehicle software in a single streamlined pipeline.
          </p>
        </div>

        <div className="flex flex-col lg:flex-row items-center justify-center gap-4 lg:gap-0">
          {steps.map((step, index) => {
            const Icon = step.icon;
            const isLast = index === steps.length - 1;
            
            return (
              <div key={step.title} className="flex items-center">
                <div className={`
                  relative glass-strong rounded-2xl p-6 w-64 transition-all duration-300
                  ${step.status === 'active' ? 'border-primary/50 shadow-glow' : ''}
                  ${step.status === 'complete' ? 'border-accent/50' : ''}
                  hover:scale-105
                `}>
                  <div className={`
                    w-10 h-10 rounded-lg flex items-center justify-center mb-4
                    ${step.status === 'active' ? 'bg-primary/20 text-primary' : ''}
                    ${step.status === 'complete' ? 'bg-accent/20 text-accent' : ''}
                    ${step.status === 'pending' ? 'bg-secondary text-muted-foreground' : ''}
                  `}>
                    <Icon className="w-5 h-5" />
                  </div>
                  
                  <h3 className="font-semibold text-foreground mb-1">{step.title}</h3>
                  <p className="text-sm text-muted-foreground">{step.description}</p>
                  
                  {step.status === 'active' && (
                    <div className="absolute -top-1 -right-1 w-3 h-3 bg-primary rounded-full animate-pulse" />
                  )}
                  {step.status === 'complete' && (
                    <div className="absolute -top-1 -right-1 w-3 h-3 bg-accent rounded-full" />
                  )}
                </div>
                
                {!isLast && (
                  <div className="hidden lg:flex items-center px-4">
                    <div className="w-8 h-px bg-gradient-to-r from-border to-primary/50" />
                    <ArrowRight className="w-4 h-4 text-primary/50 mx-1" />
                    <div className="w-8 h-px bg-gradient-to-r from-primary/50 to-border" />
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Code Preview */}
        <div className="mt-16 glass rounded-2xl p-6 overflow-hidden">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-3 h-3 rounded-full bg-destructive/80" />
            <div className="w-3 h-3 rounded-full bg-warning/80" />
            <div className="w-3 h-3 rounded-full bg-accent/80" />
            <span className="text-xs text-muted-foreground ml-2 font-mono">generated_service.cpp</span>
          </div>
          
          <pre className="font-mono text-sm overflow-x-auto">
            <code className="text-muted-foreground">
              <span className="text-primary">// Auto-generated by GenAI - AUTOSAR Compliant</span>{'\n'}
              <span className="text-accent">#include</span> <span className="text-warning">"ara/com/sample/service_skeleton.h"</span>{'\n'}
              {'\n'}
              <span className="text-accent">class</span> <span className="text-foreground">VehicleControlService</span> {'{'}
              {'\n'}  <span className="text-accent">public:</span>
              {'\n'}    <span className="text-primary">ara::core::Future</span>{'<'}<span className="text-warning">void</span>{'>'} <span className="text-foreground">ProcessSensorData</span>() {'{'}
              {'\n'}      <span className="text-muted-foreground">// Safety-critical processing with ISO 26262 compliance</span>
              {'\n'}      <span className="text-accent">return</span> executor_.Submit([<span className="text-accent">this</span>]() {'{'} ... {'}'});
              {'\n'}    {'}'}
              {'\n'}{'}'};
            </code>
          </pre>
        </div>
      </div>
    </section>
  );
};
